linters:
  # Enable all available linters.
  enable-all: true
  # Disable specific linter
  # https://golangci-lint.run/usage/linters/#disabled-by-default-linters--e--enable
  disable:
    - testpackage
    - scopelint
    - paralleltest
